### ISSUE TITLE
Thumbnails missing on Safari

### ISSUE THREAD

**Issue by UlrichFischer** [memoways/support#1]
https://tourisme.kura.media/assets

<img width="1598" alt="capture d ecran 2017-01-30 10 45 37" src="https://cloud.githubusercontent.com/assets/526276/22418887/3cecf59a-e6db-11e6-9f76-6f6952c9d876.png">

Some thumbnails are missing, but video plays back

**Comment by kuon** [comment]
Internal issue: https://github.com/memoways/kura/issues/190
