### ISSUE TITLE
Safari not updating view after interaction on assets

### ISSUE THREAD

**Issue by UlrichFischer** [memoways/support#2]
**IMPORTANT:** This issue will be public, do not include any secret or sensitive information.

### Operating System

- [X ] macOS
- [ ] Linux
- [ ] Windows

If you know the version, specify it.

### Browser

- [ X] Safari
- [ ] Chrome
- [ ] Firefox
- [ ] Other

If you know the version, specify it.

### Context information

- Space URL: <https://test.staging.kura.media/playlists>

### How would you classify the issue

- [ ] P0, blocking and all work is stopped
- [ ] P1, blocking but only for a minor part
- [ X] P2, non blocking, but affects productivity
- [ ] P3, minor/cosmetic
- [ ] PX, non issue, question, feedback

### Expected Behavior

View should refresh after interactions on assets

### Actual Behavior

View is only updated after changing from playlists to assets and playlists

### Attachments

https://www.dropbox.com/s/szthfafvr5ews5b/Kura-Safari-norefresh.mov?dl=0

**Comment by kuon** [comment]
Anything in browser's console? I cannot reproduce.
