### ISSUE TITLE
Marker editor: out point not working with drag&drop

### ISSUE THREAD

**Issue by UlrichFischer** [memoways/support#3]
**IMPORTANT:** This issue will be public, do not include any secret or sensitive information.

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows

If you know the version, specify it.

### Browser

- [X] Safari
- [x] Chrome
- [X] Firefox
- [ ] Other

If you know the version, specify it.

### Context information

- Space URL: <https://test.staging.kura.media/markers>

### How would you classify the issue

- [ ] P0, blocking and all work is stopped
- [ ] P1, blocking but only for a minor part
- [X] P2, non blocking, but affects productivity
- [ ] P3, minor/cosmetic
- [ ] PX, non issue, question, feedback

### Expected Behavior

Taking the handle of an out point of a marker should allow changing the out point

### Actual Behavior

Changing with drag&drop in point is working, but not the outpoint. Shortcuts are working, so "o" is changing the out point of the marker

### Steps to reproduce the problem

Be sure to restart the page to start from a clean state and explains all steps to reproduce the problem if you can.

Fill me in...

### Browser console output

If you can, copy the browser console output...

### Attachments

If you have any image or attachement, add them here...

**Comment by kuon** [comment]
Should be fixed
